plugins {
    // https://central.sonatype.com/artifact/org.graalvm.buildtools/native-gradle-plugin
    // id 'org.graalvm.buildtools.native' version '1.0.0'
    id 'org.graalvm.buildtools.native' version '0.11.5' apply false
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
    }

    apply plugin: 'java-library'

    java.sourceCompatibility = JavaVersion.VERSION_1_8
    compileJava.options.encoding = 'UTF-8'
    compileTestJava.options.encoding = 'UTF-8'

    version = '0.1'
    group = 'org.dreamcat.daily.script'

    dependencies {
        compileOnly libs.lombok
        annotationProcessor libs.lombok
        testCompileOnly libs.lombok
        testAnnotationProcessor libs.lombok
        testImplementation libs.jupiter.api
        testRuntimeOnly libs.jupiter.engine
        testRuntimeOnly libs.junit.platform.launcher
        implementation libs.slf4j.api

        implementation libs.common
        implementation libs.bundles.log4j2
        implementation libs.bundles.jackson
        implementation libs.jackson.yaml
        implementation libs.jackson.datatype.jsr310

        implementation libs.common.excel
        implementation libs.jsqlparser
    }

    jar {
        manifest {
            attributes "Main-Class": "org.dreamcat.daily.script.Main"
        }
    }

    tasks.register('printVersion') {
        doLast {
            print version
        }
    }

    test {
        useJUnitPlatform()
    }

    apply from: new File(rootDir, 'gradle/tasks-jar.gradle')

    createConfigurationAndJarTask('driverJar', 'all-with-drivers', 'Build a fat jar with all dependencies and all drivers', configurations.runtimeClasspath)

    dependencies {
        // https://central.sonatype.com/artifact/mysql/mysql-connector-java
        driverJar 'mysql:mysql-connector-java:8.0.33'
        // https://central.sonatype.com/artifact/org.postgresql/postgresql
        driverJar 'org.postgresql:postgresql:42.6.2'
        // https://central.sonatype.com/artifact/org.xerial/sqlite-jdbc
        driverJar 'org.xerial:sqlite-jdbc:3.50.3.0'
    }
}
