apply plugin: 'org.graalvm.buildtools.native'

dependencies {
    implementation project(":")
}

apply from: new File(rootDir, 'gradle/native-image.gradle')

graalvmNative {
    binaries {
        main {
            imageName = 'jdbc-op'
            mainClass = 'org.dreamcat.daily.script.Main'

            classpath.from(configurations.driverJar)
        }
    }
}
